version: '3.9'

services:
  amazon-s3-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: amazon-s3-api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      AWS__AccessKey: test
      AWS__SecretKey: test
      AWS__Region: us-east-1
      AWS__ServiceURL: http://localstack:4566
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
